### ISSUE TITLE
Valves not working

### ISSUE THREAD

**Issue by paulwakelin** [cow77/cbpi_BrewPi_Valve#7] opened 2019-01-17 07:56 UTC
Have 5 and 12v on valve expansion board. 1wire address recognised for each board and the temo sensors attached to each( have 3 boards), but valves still dont react? Any ideas?

**Comment by cow77** [comment] 2019-01-17 11:13
As you see the 1wire address, you should see the power leds (both 5v and 12v) lights up red.
If so, you can measure the pins for the valves (**without valve connected**). 
If you open (or close) a valve by command (button) you should see the opening or closing led turns red.
At the same time the 12v should be visible on connector (polarity depends on opening or closing).
The open/closed leds are the feedbacks of the valve internal switches.
Do you use the original Brewpi-valves?
If you don't,, most likely the pins are mixed-up (as I had myself).
You then have to find which pin is which.
Remember, there are two 12v power pins (polarity defines direction=open or close).
You have 1 common signal connected to both of the valve-internal end-switches and 2 signals for   
the other end of the switches. So you can measure the switches easy with a ohm-check.

**Comment by paulwakelin** [comment] 2019-01-17 11:30
5v and 12v LEDs are green on board, each valve has its open/closed state indicated on the board as either red or green. The valves are brewpi valves. Work when same setup plugged into brewpi spark. Should Wire 1 and 6 on cable be connected?

**Comment by cow77** [comment] 2019-01-17 11:39
Pin 1 and 6 of the cable are for rs-485, not used in this case. 

So the board has power, you see the status leds (also the opening/closing leds?).
You have connected the valve-connector the right way (not 180 degree turned).
You know the valves are ok (as they works in the brewpi spark.

Did you install the plugin? And assigned a actuator for it?

**Comment by cow77** [comment] 2019-01-17 12:53
![67f9152954297fa1](https://user-images.githubusercontent.com/5492964/51320002-d425b600-1a5e-11e9-940e-ac6491f61a4a.png)
![4865cf27bf4fafc3](https://user-images.githubusercontent.com/5492964/51320036-f15a8480-1a5e-11e9-9e73-987f85496363.png)

**Comment by paulwakelin** [comment] 2019-01-17 23:01
Yep. Leds show 5 an12v working. Leds show status of valve. Conectors are correct way round 1wire is working as it detects temp sensors and board in CBPi. Plugin installed. Actors assigned. Everything seems correct, just not getting the trigger to change valve. Is there any other apps that need to be loaded onto the RPi?

**Comment by cow77** [comment] 2019-01-18 17:28
At least we could be quite sure the hw is OK.

And then it is probably the sw where the problem is.
Did you check the logs?

I did use some test codings to find how to trigger them.
I will try to find them in the weekend.
If you use the standard 1wire connector on Pi and the temperature sensing works on the same pin, you don't need anything special. Al the 1wire software is loaded.
You should see the valve initializing (with 1wire address) in the logging of CBPi.
Something like: "Device %s Found (Family: 29, Valve on w1, GPIO4)"

**Comment by cow77** [comment] 2019-03-13 15:25
No response anymore? Closed.

**Closed as completed** 2019-03-13 15:24 UTC
